USE bone_marrow_app;

CREATE TABLE IF NOT EXISTS study_sessions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  session_id CHAR(36) NOT NULL,
  started_at DATETIME NOT NULL,
  finished_at DATETIME NULL,
  completed TINYINT(1) NOT NULL DEFAULT 0,
  age TINYINT UNSIGNED NULL,
  gender VARCHAR(20) NULL,
  donor_status VARCHAR(50) NULL,
  item_01 TINYINT UNSIGNED NULL,
  item_02 TINYINT UNSIGNED NULL,
  item_03 TINYINT UNSIGNED NULL,
  item_04 TINYINT UNSIGNED NULL,
  item_05 TINYINT UNSIGNED NULL,
  item_06 TINYINT UNSIGNED NULL,
  item_07 TINYINT UNSIGNED NULL,
  item_08 TINYINT UNSIGNED NULL,
  item_09 TINYINT UNSIGNED NULL,
  item_10 TINYINT UNSIGNED NULL,
  item_11 TINYINT UNSIGNED NULL,
  item_12 TINYINT UNSIGNED NULL,
  item_13 TINYINT UNSIGNED NULL,
  item_14 TINYINT UNSIGNED NULL,
  item_15 TINYINT UNSIGNED NULL,
  item_16 TINYINT UNSIGNED NULL,
  item_17 TINYINT UNSIGNED NULL,
  item_18 TINYINT UNSIGNED NULL,
  item_19 TINYINT UNSIGNED NULL,
  item_20 TINYINT UNSIGNED NULL,
  ext_score DECIMAL(6,2) NULL,
  agree_score DECIMAL(6,2) NULL,
  cons_score DECIMAL(6,2) NULL,
  stab_score DECIMAL(6,2) NULL,
  intell_score DECIMAL(6,2) NULL,
  z_ext DECIMAL(8,4) NULL,
  z_agree DECIMAL(8,4) NULL,
  z_cons DECIMAL(8,4) NULL,
  z_stab DECIMAL(8,4) NULL,
  z_intell DECIMAL(8,4) NULL,
  w_ext DECIMAL(8,4) NULL,
  w_agree DECIMAL(8,4) NULL,
  w_cons DECIMAL(8,4) NULL,
  w_stab DECIMAL(8,4) NULL,
  w_intell DECIMAL(8,4) NULL,
  profile_type VARCHAR(20) NULL,
  dominant_trait VARCHAR(100) NULL,
  profile_overview LONGTEXT NULL,
  communication_guidance LONGTEXT NULL,
  system_prompt_used LONGTEXT NULL,
  registration_willingness TINYINT(1) NULL,
  chosen_slot_label VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_study_sessions_session_id (session_id)
);

CREATE TABLE IF NOT EXISTS chat_messages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  study_session_id BIGINT UNSIGNED NOT NULL,
  message_order INT UNSIGNED NOT NULL,
  exchange_number INT UNSIGNED NULL,
  role ENUM('system', 'assistant', 'user') NOT NULL,
  content TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_chat_messages_session (study_session_id),
  CONSTRAINT fk_chat_messages_session
    FOREIGN KEY (study_session_id) REFERENCES study_sessions(id)
    ON DELETE CASCADE
);
